# Generated by Django 5.2.9 on 2025-12-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=25)),
                ('role', models.CharField(default='student')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleEmb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images1/')),
                ('name', models.CharField(max_length=240)),
                ('vector', models.BinaryField(default=0)),
            ],
        ),
    ]
