# Generated by Django 5.2.9 on 2025-12-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frsv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleemb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
