# Generated by Django 5.2.9 on 2025-12-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frsv', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
